/****************************************************************************
**
** Namespace stdole generated by dumpcpp from type library
** C:\Windows\system32\stdole2.tlb
**
****************************************************************************/

#ifndef QAX_DUMPCPP_STDOLE_H
#define QAX_DUMPCPP_STDOLE_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef STDOLE_EXPORT
#define STDOLE_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace stdole {

    enum LoadPictureConstants {
        Default                 = 0,
        Monochrome              = 1,
        VgaColor                = 2,
        Color                   = 4
    };

    enum OLE_TRISTATE {
        Unchecked               = 0,
        Checked                 = 1,
        Gray                    = 2
    };

// forward declarations
    struct GUID;
    struct DISPPARAMS;
    struct EXCEPINFO;
    class IUnknown;
    class IDispatch;
    class IEnumVARIANT;
    enum OLE_TRISTATE;
    class IFont;
    class IPicture;
    enum LoadPictureConstants;
    struct GUID;
    struct DISPPARAMS;
    struct EXCEPINFO;
    class IUnknown;
    class IDispatch;
    class IEnumVARIANT;
    enum OLE_TRISTATE;
    class IFont;
    class IPicture;
    enum LoadPictureConstants;

// stub for vtable-only interface
class IUnknown : public QAxObject {};

// stub for vtable-only interface
class IDispatch : public QAxObject {};

// stub for vtable-only interface
class IEnumVARIANT : public QAxObject {};

// stub for vtable-only interface
class IFont : public QAxObject {};

class STDOLE_EXPORT Font : public QAxObject
{
public:
    Font(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property Bold
    */
    inline bool Bold() const; //Returns the value of Bold
    inline void SetBold(bool value); //Sets the value of the Bold property

    /*
    Property Charset
    */
    inline int Charset() const; //Returns the value of Charset
    inline void SetCharset(int value); //Sets the value of the Charset property

    /*
    Property Italic
    */
    inline bool Italic() const; //Returns the value of Italic
    inline void SetItalic(bool value); //Sets the value of the Italic property

    /*
    Property Name
    */
    inline QString Name() const; //Returns the value of Name
    inline void SetName(const QString& value); //Sets the value of the Name property

    /*
    Property Size
    */
    inline qlonglong Size() const; //Returns the value of Size
    inline void SetSize(qlonglong value); //Sets the value of the Size property

    /*
    Property Strikethrough
    */
    inline bool Strikethrough() const; //Returns the value of Strikethrough
    inline void SetStrikethrough(bool value); //Sets the value of the Strikethrough property

    /*
    Property Underline
    */
    inline bool Underline() const; //Returns the value of Underline
    inline void SetUnderline(bool value); //Sets the value of the Underline property

    /*
    Property Weight
    */
    inline int Weight() const; //Returns the value of Weight
    inline void SetWeight(int value); //Sets the value of the Weight property

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// stub for vtable-only interface
class IPicture : public QAxObject {};

class STDOLE_EXPORT Picture : public QAxObject
{
public:
    Picture(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property Handle
    */
    inline int Handle() const; //Returns the value of Handle

    /*
    Property Height
    */
    inline int Height() const; //Returns the value of Height

    /*
    Property Type
    */
    inline int Type() const; //Returns the value of Type

    /*
    Property Width
    */
    inline int Width() const; //Returns the value of Width

    /*
    Property hPal
    */
    inline int hPal() const; //Returns the value of hPal
    inline void setHPal(int value); //Sets the value of the hPal property

    /*
    Method Render
    */
    inline void Render(int hdc, int x, int y, int cx, int cy, int xSrc, int ySrc, int cxSrc, int cySrc, void* prcWBounds);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// skipping event interface FontEvents

// Actual coclasses
class STDOLE_EXPORT StdFont : public QAxObject
{
public:
    StdFont(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl("{0be35203-8f91-11ce-9de3-00aa004bb851}");
    }

    StdFont(Font *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property Bold
    */
    inline bool Bold() const; //Returns the value of Bold
    inline void SetBold(bool value); //Sets the value of the Bold property

    /*
    Property Charset
    */
    inline int Charset() const; //Returns the value of Charset
    inline void SetCharset(int value); //Sets the value of the Charset property

    /*
    Property Italic
    */
    inline bool Italic() const; //Returns the value of Italic
    inline void SetItalic(bool value); //Sets the value of the Italic property

    /*
    Property Name
    */
    inline QString Name() const; //Returns the value of Name
    inline void SetName(const QString& value); //Sets the value of the Name property

    /*
    Property Size
    */
    inline qlonglong Size() const; //Returns the value of Size
    inline void SetSize(qlonglong value); //Sets the value of the Size property

    /*
    Property Strikethrough
    */
    inline bool Strikethrough() const; //Returns the value of Strikethrough
    inline void SetStrikethrough(bool value); //Sets the value of the Strikethrough property

    /*
    Property Underline
    */
    inline bool Underline() const; //Returns the value of Underline
    inline void SetUnderline(bool value); //Sets the value of the Underline property

    /*
    Property Weight
    */
    inline int Weight() const; //Returns the value of Weight
    inline void SetWeight(int value); //Sets the value of the Weight property

    /*
    Property hFont
    */
    inline int* hFont() const; //Returns the value of hFont

    /*
    Method AddRefHfont
    */
    inline void AddRefHfont(int hFont);

    /*
    Method Clone
    */
    inline void Clone(QFont& ppfont);

    /*
    Method IsEqual
    */
    inline void IsEqual(const QFont& pfontOther);

    /*
    Method ReleaseHfont
    */
    inline void ReleaseHfont(int hFont);

    /*
    Method SetRatio
    */
    inline void SetRatio(int cyLogical, int cyHimetric);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class STDOLE_EXPORT StdPicture : public QAxObject
{
public:
    StdPicture(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl("{0be35204-8f91-11ce-9de3-00aa004bb851}");
    }

    StdPicture(Picture *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property Attributes
    */
    inline int Attributes() const; //Returns the value of Attributes

    /*
    Property CurDC
    */
    inline int CurDC() const; //Returns the value of CurDC

    /*
    Property Handle
    */
    inline int* Handle() const; //Returns the value of Handle

    /*
    Property Height
    */
    inline int* Height() const; //Returns the value of Height

    /*
    Property KeepOriginalFormat
    */
    inline bool KeepOriginalFormat() const; //Returns the value of KeepOriginalFormat
    inline void SetKeepOriginalFormat(bool value); //Sets the value of the KeepOriginalFormat property

    /*
    Property Type
    */
    inline int Type() const; //Returns the value of Type

    /*
    Property Width
    */
    inline int* Width() const; //Returns the value of Width

    /*
    Property hPal
    */
    inline int hPal() const; //Returns the value of hPal
    inline void setHPal(int value); //Sets the value of the hPal property

    /*
    Method PictureChanged
    */
    inline void PictureChanged();

    /*
    Method Render
    */
    inline void Render(int hdc, int x, int y, int cx, int cy, int xSrc, int ySrc, int cxSrc, int cySrc, void* prcWBounds);

    /*
    Method SaveAsFile
    */
    inline void SaveAsFile(void* pstm, bool fSaveMemCopy, int& pcbSize);

    /*
    Method SelectPicture
    */
    inline void SelectPicture(int hdcIn, int& phdcOut, int*& phbmpOut);

    /*
    Method SetHdc
    */
    inline void SetHdc(int hdc);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_STDOLE_NOINLINES
inline bool Font::Bold() const
{
    QVariant qax_result = property("Bold");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void Font::SetBold(bool value){ setProperty("Bold", QVariant(value)); }

inline int Font::Charset() const
{
    QVariant qax_result = property("Charset");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void Font::SetCharset(int value){ setProperty("Charset", QVariant(value)); }

inline bool Font::Italic() const
{
    QVariant qax_result = property("Italic");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void Font::SetItalic(bool value){ setProperty("Italic", QVariant(value)); }

inline QString Font::Name() const
{
    QVariant qax_result = property("Name");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void Font::SetName(const QString& value){ setProperty("Name", QVariant(value)); }

inline qlonglong Font::Size() const
{
    QVariant qax_result = property("Size");
    Q_ASSERT(qax_result.isValid());
    return *(qlonglong*)qax_result.constData();
}
inline void Font::SetSize(qlonglong value){ setProperty("Size", QVariant(value)); }

inline bool Font::Strikethrough() const
{
    QVariant qax_result = property("Strikethrough");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void Font::SetStrikethrough(bool value){ setProperty("Strikethrough", QVariant(value)); }

inline bool Font::Underline() const
{
    QVariant qax_result = property("Underline");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void Font::SetUnderline(bool value){ setProperty("Underline", QVariant(value)); }

inline int Font::Weight() const
{
    QVariant qax_result = property("Weight");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void Font::SetWeight(int value){ setProperty("Weight", QVariant(value)); }


inline bool StdFont::Bold() const
{
    QVariant qax_result = property("Bold");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void StdFont::SetBold(bool value){ setProperty("Bold", QVariant(value)); }

inline int StdFont::Charset() const
{
    QVariant qax_result = property("Charset");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void StdFont::SetCharset(int value){ setProperty("Charset", QVariant(value)); }

inline bool StdFont::Italic() const
{
    QVariant qax_result = property("Italic");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void StdFont::SetItalic(bool value){ setProperty("Italic", QVariant(value)); }

inline QString StdFont::Name() const
{
    QVariant qax_result = property("Name");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void StdFont::SetName(const QString& value){ setProperty("Name", QVariant(value)); }

inline qlonglong StdFont::Size() const
{
    QVariant qax_result = property("Size");
    Q_ASSERT(qax_result.isValid());
    return *(qlonglong*)qax_result.constData();
}
inline void StdFont::SetSize(qlonglong value){ setProperty("Size", QVariant(value)); }

inline bool StdFont::Strikethrough() const
{
    QVariant qax_result = property("Strikethrough");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void StdFont::SetStrikethrough(bool value){ setProperty("Strikethrough", QVariant(value)); }

inline bool StdFont::Underline() const
{
    QVariant qax_result = property("Underline");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void StdFont::SetUnderline(bool value){ setProperty("Underline", QVariant(value)); }

inline int StdFont::Weight() const
{
    QVariant qax_result = property("Weight");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void StdFont::SetWeight(int value){ setProperty("Weight", QVariant(value)); }

inline int* StdFont::hFont() const
{
    QVariant qax_result = property("hFont");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(int**)qax_result.constData();
}

inline void StdFont::AddRefHfont(int hFont)
{
    void *_a[] = {0, (void*)&hFont};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void StdFont::Clone(QFont& ppfont)
{
    void *_a[] = {0, (void*)&ppfont};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void StdFont::IsEqual(const QFont& pfontOther)
{
    void *_a[] = {0, (void*)&pfontOther};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void StdFont::ReleaseHfont(int hFont)
{
    void *_a[] = {0, (void*)&hFont};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
}

inline void StdFont::SetRatio(int cyLogical, int cyHimetric)
{
    void *_a[] = {0, (void*)&cyLogical, (void*)&cyHimetric};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
}


inline int Picture::Handle() const
{
    QVariant qax_result = property("Handle");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int Picture::Height() const
{
    QVariant qax_result = property("Height");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int Picture::Type() const
{
    QVariant qax_result = property("Type");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int Picture::Width() const
{
    QVariant qax_result = property("Width");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int Picture::hPal() const
{
    QVariant qax_result = property("hPal");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void Picture::setHPal(int value){ setProperty("hPal", QVariant(value)); }

inline void Picture::Render(int hdc, int x, int y, int cx, int cy, int xSrc, int ySrc, int cxSrc, int cySrc, void* prcWBounds)
{
    void *_a[] = {0, (void*)&hdc, (void*)&x, (void*)&y, (void*)&cx, (void*)&cy, (void*)&xSrc, (void*)&ySrc, (void*)&cxSrc, (void*)&cySrc, (void*)&prcWBounds};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}


inline int StdPicture::Attributes() const
{
    QVariant qax_result = property("Attributes");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int StdPicture::CurDC() const
{
    QVariant qax_result = property("CurDC");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int* StdPicture::Handle() const
{
    QVariant qax_result = property("Handle");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(int**)qax_result.constData();
}

inline int* StdPicture::Height() const
{
    QVariant qax_result = property("Height");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(int**)qax_result.constData();
}

inline bool StdPicture::KeepOriginalFormat() const
{
    QVariant qax_result = property("KeepOriginalFormat");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void StdPicture::SetKeepOriginalFormat(bool value){ setProperty("KeepOriginalFormat", QVariant(value)); }

inline int StdPicture::Type() const
{
    QVariant qax_result = property("Type");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int* StdPicture::Width() const
{
    QVariant qax_result = property("Width");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(int**)qax_result.constData();
}

inline int StdPicture::hPal() const
{
    QVariant qax_result = property("hPal");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void StdPicture::setHPal(int value){ setProperty("hPal", QVariant(value)); }

inline void StdPicture::PictureChanged()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void StdPicture::Render(int hdc, int x, int y, int cx, int cy, int xSrc, int ySrc, int cxSrc, int cySrc, void* prcWBounds)
{
    void *_a[] = {0, (void*)&hdc, (void*)&x, (void*)&y, (void*)&cx, (void*)&cy, (void*)&xSrc, (void*)&ySrc, (void*)&cxSrc, (void*)&cySrc, (void*)&prcWBounds};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline void StdPicture::SaveAsFile(void* pstm, bool fSaveMemCopy, int& pcbSize)
{
    void *_a[] = {0, (void*)&pstm, (void*)&fSaveMemCopy, (void*)&pcbSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
}

inline void StdPicture::SelectPicture(int hdcIn, int& phdcOut, int*& phbmpOut)
{
    void *_a[] = {0, (void*)&hdcIn, (void*)&phdcOut, (void*)&phbmpOut};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
}

inline void StdPicture::SetHdc(int hdc)
{
    void *_a[] = {0, (void*)&hdc};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<stdole::Font, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<stdole::Font*>(t)->stdole::Font::~Font();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) stdole::Font;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const stdole::Font*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<stdole::Font*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<stdole::StdFont, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<stdole::StdFont*>(t)->stdole::StdFont::~StdFont();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) stdole::StdFont;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const stdole::StdFont*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<stdole::StdFont*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<stdole::Picture, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<stdole::Picture*>(t)->stdole::Picture::~Picture();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) stdole::Picture;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const stdole::Picture*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<stdole::Picture*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<stdole::StdPicture, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<stdole::StdPicture*>(t)->stdole::StdPicture::~StdPicture();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) stdole::StdPicture;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const stdole::StdPicture*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<stdole::StdPicture*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

