/****************************************************************************
**
** Namespace VBA generated by dumpcpp from type library
** C:\Windows\system32\msvbvm60.dll
**
****************************************************************************/

#ifndef QAX_DUMPCPP_VBA_H
#define QAX_DUMPCPP_VBA_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef VBA_EXPORT
#define VBA_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace VBA {

    enum VbAppWinStyle {
        vbHide                  = 0,
        vbNormalFocus           = 1,
        vbMinimizedFocus        = 2,
        vbMaximizedFocus        = 3,
        vbNormalNoFocus         = 4,
        vbMinimizedNoFocus      = 6
    };

    enum VbCalendar {
        vbCalGreg               = 0,
        vbCalHijri              = 1
    };

    enum VbCallType {
        VbMethod                = 1,
        VbGet                   = 2,
        VbLet                   = 4,
        VbSet                   = 8
    };

    enum VbCompareMethod {
        vbBinaryCompare         = 0,
        vbTextCompare           = 1,
        vbDatabaseCompare       = 2
    };

    enum VbDateTimeFormat {
        vbGeneralDate           = 0,
        vbLongDate              = 1,
        vbShortDate             = 2,
        vbLongTime              = 3,
        vbShortTime             = 4
    };

    enum VbDayOfWeek {
        vbUseSystemDayOfWeek    = 0,
        vbSunday                = 1,
        vbMonday                = 2,
        vbTuesday               = 3,
        vbWednesday             = 4,
        vbThursday              = 5,
        vbFriday                = 6,
        vbSaturday              = 7
    };

    enum VbFileAttribute {
        vbNormal                = 0,
        vbReadOnly              = 1,
        vbHidden                = 2,
        vbSystem                = 4,
        vbVolume                = 8,
        vbDirectory             = 16,
        vbArchive               = 32,
        vbAlias                 = 64
    };

    enum VbFirstWeekOfYear {
        vbUseSystem             = 0,
        vbFirstJan1             = 1,
        vbFirstFourDays         = 2,
        vbFirstFullWeek         = 3
    };

    enum VbIMEStatus {
        vbIMENoOp               = 0,
        vbIMEModeNoControl      = 0,
        vbIMEOn                 = 1,
        vbIMEModeOn             = 1,
        vbIMEOff                = 2,
        vbIMEModeOff            = 2,
        vbIMEDisable            = 3,
        vbIMEModeDisable        = 3,
        vbIMEHiragana           = 4,
        vbIMEModeHiragana       = 4,
        vbIMEKatakanaDbl        = 5,
        vbIMEModeKatakana       = 5,
        vbIMEKatakanaSng        = 6,
        vbIMEModeKatakanaHalf   = 6,
        vbIMEAlphaDbl           = 7,
        vbIMEModeAlphaFull      = 7,
        vbIMEAlphaSng           = 8,
        vbIMEModeAlpha          = 8,
        vbIMEModeHangulFull     = 9,
        vbIMEModeHangul         = 10
    };

    enum VbMsgBoxResult {
        vbOK                    = 1,
        vbCancel                = 2,
        vbAbort                 = 3,
        vbRetry                 = 4,
        vbIgnore                = 5,
        vbYes                   = 6,
        vbNo                    = 7
    };

    enum VbMsgBoxStyle {
        vbOKOnly                = 0,
        vbOKCancel              = 1,
        vbAbortRetryIgnore      = 2,
        vbYesNoCancel           = 3,
        vbYesNo                 = 4,
        vbRetryCancel           = 5,
        vbCritical              = 16,
        vbQuestion              = 32,
        vbExclamation           = 48,
        vbInformation           = 64,
        vbDefaultButton1        = 0,
        vbDefaultButton2        = 256,
        vbDefaultButton3        = 512,
        vbDefaultButton4        = 768,
        vbApplicationModal      = 0,
        vbSystemModal           = 4096,
        vbMsgBoxHelpButton      = 16384,
        vbMsgBoxRight           = 524288,
        vbMsgBoxRtlReading      = 1048576,
        vbMsgBoxSetForeground   = 65536
    };

    enum VbStrConv {
        vbUpperCase             = 1,
        vbLowerCase             = 2,
        vbProperCase            = 3,
        vbWide                  = 4,
        vbNarrow                = 8,
        vbKatakana              = 16,
        vbHiragana              = 32,
        vbUnicode               = 64,
        vbFromUnicode           = 128
    };

    enum VbTriState {
        vbUseDefault            = -2,
        vbTrue                  = -1,
        vbFalse                 = 0
    };

    enum VbVarType {
        vbEmpty                 = 0,
        vbNull                  = 1,
        vbInteger               = 2,
        vbLong                  = 3,
        vbSingle                = 4,
        vbDouble                = 5,
        vbCurrency              = 6,
        vbDate                  = 7,
        vbString                = 8,
        vbObject                = 9,
        vbError                 = 10,
        vbBoolean               = 11,
        vbVariant               = 12,
        vbDataObject            = 13,
        vbDecimal               = 14,
        vbByte                  = 17,
        vbUserDefinedType       = 36,
        vbArray                 = 8192
    };

// forward declarations
    enum VbVarType;
    enum VbMsgBoxStyle;
    enum VbMsgBoxResult;
    enum VbFileAttribute;
    enum VbStrConv;
    enum VbDayOfWeek;
    enum VbFirstWeekOfYear;
    enum VbIMEStatus;
    enum VbAppWinStyle;
    enum VbCompareMethod;
    enum VbCalendar;
    enum VbDateTimeFormat;
    enum VbTriState;
    enum VbCallType;
    class _HiddenInterface;
    enum VbVarType;
    enum VbMsgBoxStyle;
    enum VbMsgBoxResult;
    enum VbFileAttribute;
    enum VbStrConv;
    enum VbDayOfWeek;
    enum VbFirstWeekOfYear;
    enum VbIMEStatus;
    enum VbAppWinStyle;
    enum VbCompareMethod;
    enum VbCalendar;
    enum VbDateTimeFormat;
    enum VbTriState;
    enum VbCallType;
    class _HiddenInterface;

// stub for vtable-only interface
class _HiddenInterface : public QAxObject {};

class VBA_EXPORT _ErrObject : public QAxObject
{
public:
    _ErrObject(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property Description

    For more information, see help context 1014191 in C:\Windows\system32\VBA.HLP.
    */
    inline QString Description() const; //Returns the value of Description
    inline void SetDescription(const QString& value); //Sets the value of the Description property

    /*
    Property HelpContext

    For more information, see help context 1014190 in C:\Windows\system32\VBA.HLP.
    */
    inline int HelpContext() const; //Returns the value of HelpContext
    inline void SetHelpContext(int value); //Sets the value of the HelpContext property

    /*
    Property HelpFile

    For more information, see help context 1014189 in C:\Windows\system32\VBA.HLP.
    */
    inline QString HelpFile() const; //Returns the value of HelpFile
    inline void SetHelpFile(const QString& value); //Sets the value of the HelpFile property

    /*
    Property LastDllError

    For more information, see help context 1020108 in C:\Windows\system32\VBA.HLP.
    */
    inline int LastDllError() const; //Returns the value of LastDllError

    /*
    Property Number

    For more information, see help context 1014186 in C:\Windows\system32\VBA.HLP.
    */
    inline int Number() const; //Returns the value of Number
    inline void SetNumber(int value); //Sets the value of the Number property

    /*
    Property Source

    For more information, see help context 1014188 in C:\Windows\system32\VBA.HLP.
    */
    inline QString Source() const; //Returns the value of Source
    inline void SetSource(const QString& value); //Sets the value of the Source property

    /*
    Method Clear

    For more information, see help context 1014184 in C:\Windows\system32\VBA.HLP.
    */
    inline void Clear();

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number);

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number, QVariant& Source);

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number, QVariant& Source, QVariant& Description);

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number, QVariant& Source, QVariant& Description, QVariant& HelpFile);

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number, QVariant& Source, QVariant& Description, QVariant& HelpFile, QVariant& HelpContext);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class VBA_EXPORT _Collection : public QAxObject
{
public:
    _Collection(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method Add

    For more information, see help context 1014017 in C:\Windows\system32\VBA.HLP.
    */
    inline void Add(QVariant& Item);

    /*
    Method Add

    For more information, see help context 1014017 in C:\Windows\system32\VBA.HLP.
    */
    inline void Add(QVariant& Item, QVariant& Key);

    /*
    Method Add

    For more information, see help context 1014017 in C:\Windows\system32\VBA.HLP.
    */
    inline void Add(QVariant& Item, QVariant& Key, QVariant& Before);

    /*
    Method Add

    For more information, see help context 1014017 in C:\Windows\system32\VBA.HLP.
    */
    inline void Add(QVariant& Item, QVariant& Key, QVariant& Before, QVariant& After);

    /*
    Method Count

    For more information, see help context 1014018 in C:\Windows\system32\VBA.HLP.
    */
    inline int Count();

    /*
    Method Item

    For more information, see help context 1014019 in C:\Windows\system32\VBA.HLP.
    */
    inline QVariant Item(QVariant& Index);

    /*
    Method Remove

    For more information, see help context 1014020 in C:\Windows\system32\VBA.HLP.
    */
    inline void Remove(QVariant& Index);

    /*
    Method _NewEnum

    For more information, see help context 0 in C:\Windows\system32\VBA.HLP.
    */
    inline IUnknown* _NewEnum();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class VBA_EXPORT ErrObject : public QAxObject
{
public:
    ErrObject(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl("{a4c46654-499f-101b-bb78-00aa00383cbb}");
    }

    /*
    Property Description

    For more information, see help context 1014191 in C:\Windows\system32\VBA.HLP.
    */
    inline QString Description() const; //Returns the value of Description
    inline void SetDescription(const QString& value); //Sets the value of the Description property

    /*
    Property HelpContext

    For more information, see help context 1014190 in C:\Windows\system32\VBA.HLP.
    */
    inline int HelpContext() const; //Returns the value of HelpContext
    inline void SetHelpContext(int value); //Sets the value of the HelpContext property

    /*
    Property HelpFile

    For more information, see help context 1014189 in C:\Windows\system32\VBA.HLP.
    */
    inline QString HelpFile() const; //Returns the value of HelpFile
    inline void SetHelpFile(const QString& value); //Sets the value of the HelpFile property

    /*
    Property LastDllError

    For more information, see help context 1020108 in C:\Windows\system32\VBA.HLP.
    */
    inline int LastDllError() const; //Returns the value of LastDllError

    /*
    Property Number

    For more information, see help context 1014186 in C:\Windows\system32\VBA.HLP.
    */
    inline int Number() const; //Returns the value of Number
    inline void SetNumber(int value); //Sets the value of the Number property

    /*
    Property Source

    For more information, see help context 1014188 in C:\Windows\system32\VBA.HLP.
    */
    inline QString Source() const; //Returns the value of Source
    inline void SetSource(const QString& value); //Sets the value of the Source property

    /*
    Method Clear

    For more information, see help context 1014184 in C:\Windows\system32\VBA.HLP.
    */
    inline void Clear();

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number);

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number, QVariant& Source);

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number, QVariant& Source, QVariant& Description);

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number, QVariant& Source, QVariant& Description, QVariant& HelpFile);

    /*
    Method Raise

    For more information, see help context 1014183 in C:\Windows\system32\VBA.HLP.
    */
    inline void Raise(int Number, QVariant& Source, QVariant& Description, QVariant& HelpFile, QVariant& HelpContext);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class VBA_EXPORT Collection : public QAxObject
{
public:
    Collection(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl("{a4c4671c-499f-101b-bb78-00aa00383cbb}");
    }

    /*
    Method Add

    For more information, see help context 1014017 in C:\Windows\system32\VBA.HLP.
    */
    inline void Add(QVariant& Item);

    /*
    Method Add

    For more information, see help context 1014017 in C:\Windows\system32\VBA.HLP.
    */
    inline void Add(QVariant& Item, QVariant& Key);

    /*
    Method Add

    For more information, see help context 1014017 in C:\Windows\system32\VBA.HLP.
    */
    inline void Add(QVariant& Item, QVariant& Key, QVariant& Before);

    /*
    Method Add

    For more information, see help context 1014017 in C:\Windows\system32\VBA.HLP.
    */
    inline void Add(QVariant& Item, QVariant& Key, QVariant& Before, QVariant& After);

    /*
    Method Count

    For more information, see help context 1014018 in C:\Windows\system32\VBA.HLP.
    */
    inline int Count();

    /*
    Method Item

    For more information, see help context 1014019 in C:\Windows\system32\VBA.HLP.
    */
    inline QVariant Item(QVariant& Index);

    /*
    Method Remove

    For more information, see help context 1014020 in C:\Windows\system32\VBA.HLP.
    */
    inline void Remove(QVariant& Index);

    /*
    Method _NewEnum

    For more information, see help context 0 in C:\Windows\system32\VBA.HLP.
    */
    inline IUnknown* _NewEnum();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_VBA_NOINLINES
inline QString _ErrObject::Description() const
{
    QVariant qax_result = property("Description");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void _ErrObject::SetDescription(const QString& value){ setProperty("Description", QVariant(value)); }

inline int _ErrObject::HelpContext() const
{
    QVariant qax_result = property("HelpContext");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _ErrObject::SetHelpContext(int value){ setProperty("HelpContext", QVariant(value)); }

inline QString _ErrObject::HelpFile() const
{
    QVariant qax_result = property("HelpFile");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void _ErrObject::SetHelpFile(const QString& value){ setProperty("HelpFile", QVariant(value)); }

inline int _ErrObject::LastDllError() const
{
    QVariant qax_result = property("LastDllError");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int _ErrObject::Number() const
{
    QVariant qax_result = property("Number");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _ErrObject::SetNumber(int value){ setProperty("Number", QVariant(value)); }

inline QString _ErrObject::Source() const
{
    QVariant qax_result = property("Source");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void _ErrObject::SetSource(const QString& value){ setProperty("Source", QVariant(value)); }

inline void _ErrObject::Clear()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void _ErrObject::Raise(int Number)
{
    void *_a[] = {0, (void*)&Number};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void _ErrObject::Raise(int Number, QVariant& Source)
{
    void *_a[] = {0, (void*)&Number, (void*)&Source};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline void _ErrObject::Raise(int Number, QVariant& Source, QVariant& Description)
{
    void *_a[] = {0, (void*)&Number, (void*)&Source, (void*)&Description};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline void _ErrObject::Raise(int Number, QVariant& Source, QVariant& Description, QVariant& HelpFile)
{
    void *_a[] = {0, (void*)&Number, (void*)&Source, (void*)&Description, (void*)&HelpFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void _ErrObject::Raise(int Number, QVariant& Source, QVariant& Description, QVariant& HelpFile, QVariant& HelpContext)
{
    void *_a[] = {0, (void*)&Number, (void*)&Source, (void*)&Description, (void*)&HelpFile, (void*)&HelpContext};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}


inline QString ErrObject::Description() const
{
    QVariant qax_result = property("Description");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ErrObject::SetDescription(const QString& value){ setProperty("Description", QVariant(value)); }

inline int ErrObject::HelpContext() const
{
    QVariant qax_result = property("HelpContext");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void ErrObject::SetHelpContext(int value){ setProperty("HelpContext", QVariant(value)); }

inline QString ErrObject::HelpFile() const
{
    QVariant qax_result = property("HelpFile");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ErrObject::SetHelpFile(const QString& value){ setProperty("HelpFile", QVariant(value)); }

inline int ErrObject::LastDllError() const
{
    QVariant qax_result = property("LastDllError");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int ErrObject::Number() const
{
    QVariant qax_result = property("Number");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void ErrObject::SetNumber(int value){ setProperty("Number", QVariant(value)); }

inline QString ErrObject::Source() const
{
    QVariant qax_result = property("Source");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ErrObject::SetSource(const QString& value){ setProperty("Source", QVariant(value)); }

inline void ErrObject::Clear()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void ErrObject::Raise(int Number)
{
    void *_a[] = {0, (void*)&Number};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void ErrObject::Raise(int Number, QVariant& Source)
{
    void *_a[] = {0, (void*)&Number, (void*)&Source};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline void ErrObject::Raise(int Number, QVariant& Source, QVariant& Description)
{
    void *_a[] = {0, (void*)&Number, (void*)&Source, (void*)&Description};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline void ErrObject::Raise(int Number, QVariant& Source, QVariant& Description, QVariant& HelpFile)
{
    void *_a[] = {0, (void*)&Number, (void*)&Source, (void*)&Description, (void*)&HelpFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void ErrObject::Raise(int Number, QVariant& Source, QVariant& Description, QVariant& HelpFile, QVariant& HelpContext)
{
    void *_a[] = {0, (void*)&Number, (void*)&Source, (void*)&Description, (void*)&HelpFile, (void*)&HelpContext};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}


inline void _Collection::Add(QVariant& Item)
{
    void *_a[] = {0, (void*)&Item};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void _Collection::Add(QVariant& Item, QVariant& Key)
{
    void *_a[] = {0, (void*)&Item, (void*)&Key};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void _Collection::Add(QVariant& Item, QVariant& Key, QVariant& Before)
{
    void *_a[] = {0, (void*)&Item, (void*)&Key, (void*)&Before};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline void _Collection::Add(QVariant& Item, QVariant& Key, QVariant& Before, QVariant& After)
{
    void *_a[] = {0, (void*)&Item, (void*)&Key, (void*)&Before, (void*)&After};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline int _Collection::Count()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline QVariant _Collection::Item(QVariant& Index)
{
    QVariant qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&Index};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline void _Collection::Remove(QVariant& Index)
{
    void *_a[] = {0, (void*)&Index};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline IUnknown* _Collection::_NewEnum()
{
    IUnknown* qax_result = 0;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}


inline void Collection::Add(QVariant& Item)
{
    void *_a[] = {0, (void*)&Item};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void Collection::Add(QVariant& Item, QVariant& Key)
{
    void *_a[] = {0, (void*)&Item, (void*)&Key};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void Collection::Add(QVariant& Item, QVariant& Key, QVariant& Before)
{
    void *_a[] = {0, (void*)&Item, (void*)&Key, (void*)&Before};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline void Collection::Add(QVariant& Item, QVariant& Key, QVariant& Before, QVariant& After)
{
    void *_a[] = {0, (void*)&Item, (void*)&Key, (void*)&Before, (void*)&After};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline int Collection::Count()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline QVariant Collection::Item(QVariant& Index)
{
    QVariant qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&Index};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline void Collection::Remove(QVariant& Index)
{
    void *_a[] = {0, (void*)&Index};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline IUnknown* Collection::_NewEnum()
{
    IUnknown* qax_result = 0;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<VBA::_ErrObject, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VBA::_ErrObject*>(t)->VBA::_ErrObject::~_ErrObject();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VBA::_ErrObject;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VBA::_ErrObject*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VBA::_ErrObject*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<VBA::ErrObject, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VBA::ErrObject*>(t)->VBA::ErrObject::~ErrObject();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VBA::ErrObject;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VBA::ErrObject*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VBA::ErrObject*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<VBA::_Collection, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VBA::_Collection*>(t)->VBA::_Collection::~_Collection();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VBA::_Collection;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VBA::_Collection*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VBA::_Collection*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<VBA::Collection, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VBA::Collection*>(t)->VBA::Collection::~Collection();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VBA::Collection;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VBA::Collection*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VBA::Collection*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

