#ifndef EXCELCVSMODEL_GLOBAL_H
#define EXCELCVSMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXCELCVSMODEL_LIBRARY)
#  define EXCELCVSMODEL_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXCELCVSMODEL_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXCELCVSMODEL_GLOBAL_H
