#ifndef EXCALCVSADDINCONTROLLER_GLOBAL_H
#define EXCALCVSADDINCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXCELCVSADDINCONTROLLER_LIBRARY)
#  define EXCALCVSADDINCONTROLLER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXCALCVSADDINCONTROLLER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXCALCVSADDINCONTROLLER_GLOBAL_H
