#ifndef ACCESSCVSMODEL_GLOBAL_H
#define ACCESSCVSMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACCESSCVSMODEL_LIBRARY)
#  define ACCESSCVSMODEL_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACCESSCVSMODEL_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACCESSCVSMODEL_GLOBAL_H
