#ifndef CVSCONTROLLER_GLOBAL_H
#define CVSCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CVSCONTROLLER_LIBRARY)
#  define CVSCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CVSCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CVSCONTROLLER_GLOBAL_H
