#ifndef CVSADDINCONTROLLER_GLOBAL_H
#define CVSADDINCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CVSADDINCONTROLLER_LIBRARY)
#  define CVSADDINCONTROLLER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define CVSADDINCONTROLLER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CVSADDINCONTROLLER_GLOBAL_H
