#ifndef ACCESSCONTROLLER_GLOBAL_H
#define ACCESSCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACCESSCONTROLLER_LIBRARY)
#  define ACCESSCONTROLLER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACCESSCONTROLLER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACCESSCONTROLLER_GLOBAL_H
