#ifndef ACCESSADDINCONTROLLER_GLOBAL_H
#define ACCESSADDINCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACCESSADDINCONTROLLER_LIBRARY)
#  define ACCESSADDINCONTROLLER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACCESSADDINCONTROLLER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACCESSADDINCONTROLLER_GLOBAL_H
