#ifndef ACCESSUTIL_GLOBAL_H
#define ACCESSUTIL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACCESSUTIL_LIBRARY)
#  define ACCESSUTILSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACCESSUTILSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACCESSUTIL_GLOBAL_H
