#ifndef GITCONTROLLER_GLOBAL_H
#define GITCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GITCONTROLLER_LIBRARY)
#  define GITCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GITCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GITCONTROLLER_GLOBAL_H
