#ifndef ACCCONTROLLER_GLOBAL_H
#define ACCCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACCCONTROLLER_LIBRARY)
#  define ACCCONTROLLER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACCCONTROLLER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACCCONTROLLER_GLOBAL_H
