#ifndef ACCESSUTILCONTROLLER_GLOBAL_H
#define ACCESSUTILCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACCESSUTILCONTROLLER_LIBRARY)
#  define ACCESSUTILCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACCESSUTILCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACCESSUTILCONTROLLER_GLOBAL_H
