/****************************************************************************
**
** Metadata for stdole generated by dumpcpp from type library
** C:\Windows\system32\stdole2.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_STDOLE_NOINLINES
#include "stdole.h"

using namespace stdole;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[91];
    char stringdata0[793];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 12, 0),
QT_MOC_LITERAL(1, 13, 9, 0),
QT_MOC_LITERAL(2, 23, 0, 0),
QT_MOC_LITERAL(3, 24, 4, 0),
QT_MOC_LITERAL(4, 29, 6, 0),
QT_MOC_LITERAL(5, 36, 4, 0),
QT_MOC_LITERAL(6, 41, 4, 0),
QT_MOC_LITERAL(7, 46, 15, 0),
QT_MOC_LITERAL(8, 62, 4, 0),
QT_MOC_LITERAL(9, 67, 6, 0),
QT_MOC_LITERAL(10, 74, 4, 0),
QT_MOC_LITERAL(11, 79, 4, 0),
QT_MOC_LITERAL(12, 84, 7, 0),
QT_MOC_LITERAL(13, 92, 4, 0),
QT_MOC_LITERAL(14, 97, 10, 0),
QT_MOC_LITERAL(15, 108, 7, 0),
QT_MOC_LITERAL(16, 116, 9, 0),
QT_MOC_LITERAL(17, 126, 6, 0),
QT_MOC_LITERAL(18, 133, 7, 0),
QT_MOC_LITERAL(19, 141, 4, 0),
QT_MOC_LITERAL(20, 146, 7, 0),
QT_MOC_LITERAL(21, 154, 4, 0),
QT_MOC_LITERAL(22, 159, 16, 0),
QT_MOC_LITERAL(23, 176, 13, 0),
QT_MOC_LITERAL(24, 190, 12, 0),
QT_MOC_LITERAL(25, 203, 9, 0),
QT_MOC_LITERAL(26, 213, 9, 0),
QT_MOC_LITERAL(27, 223, 6, 0),
QT_MOC_LITERAL(28, 230, 7, 0),
QT_MOC_LITERAL(29, 238, 20, 0),
QT_MOC_LITERAL(30, 259, 7, 0),
QT_MOC_LITERAL(31, 267, 10, 0),
QT_MOC_LITERAL(32, 278, 8, 0),
QT_MOC_LITERAL(33, 287, 5, 0),
QT_MOC_LITERAL(34, 293, 12, 0),
QT_MOC_LITERAL(35, 306, 9, 0),
QT_MOC_LITERAL(36, 316, 7, 0),
QT_MOC_LITERAL(37, 324, 4, 0),
QT_MOC_LITERAL(38, 329, 15, 0),
QT_MOC_LITERAL(39, 345, 11, 0),
QT_MOC_LITERAL(40, 357, 4, 0),
QT_MOC_LITERAL(41, 362, 11, 0),
QT_MOC_LITERAL(42, 374, 12, 0),
QT_MOC_LITERAL(43, 387, 11, 0),
QT_MOC_LITERAL(44, 399, 5, 0),
QT_MOC_LITERAL(45, 405, 5, 0),
QT_MOC_LITERAL(46, 411, 6, 0),
QT_MOC_LITERAL(47, 418, 6, 0),
QT_MOC_LITERAL(48, 425, 7, 0),
QT_MOC_LITERAL(49, 433, 10, 0),
QT_MOC_LITERAL(50, 444, 12, 0),
QT_MOC_LITERAL(51, 457, 8, 0),
QT_MOC_LITERAL(52, 466, 9, 0),
QT_MOC_LITERAL(53, 476, 10, 0),
QT_MOC_LITERAL(54, 487, 4, 0),
QT_MOC_LITERAL(55, 492, 15, 0),
QT_MOC_LITERAL(56, 508, 6, 0),
QT_MOC_LITERAL(57, 515, 3, 0),
QT_MOC_LITERAL(58, 519, 1, 0),
QT_MOC_LITERAL(59, 521, 1, 0),
QT_MOC_LITERAL(60, 523, 2, 0),
QT_MOC_LITERAL(61, 526, 2, 0),
QT_MOC_LITERAL(62, 529, 4, 0),
QT_MOC_LITERAL(63, 534, 4, 0),
QT_MOC_LITERAL(64, 539, 5, 0),
QT_MOC_LITERAL(65, 545, 5, 0),
QT_MOC_LITERAL(66, 551, 10, 0),
QT_MOC_LITERAL(67, 562, 7, 0),
QT_MOC_LITERAL(68, 570, 4, 0),
QT_MOC_LITERAL(69, 575, 6, 0),
QT_MOC_LITERAL(70, 582, 6, 0),
QT_MOC_LITERAL(71, 589, 4, 0),
QT_MOC_LITERAL(72, 594, 5, 0),
QT_MOC_LITERAL(73, 600, 18, 0),
QT_MOC_LITERAL(74, 619, 7, 0),
QT_MOC_LITERAL(75, 627, 10, 0),
QT_MOC_LITERAL(76, 638, 5, 0),
QT_MOC_LITERAL(77, 644, 18, 0),
QT_MOC_LITERAL(78, 663, 14, 0),
QT_MOC_LITERAL(79, 678, 10, 0),
QT_MOC_LITERAL(80, 689, 4, 0),
QT_MOC_LITERAL(81, 694, 12, 0),
QT_MOC_LITERAL(82, 707, 4, 0),
QT_MOC_LITERAL(83, 712, 7, 0),
QT_MOC_LITERAL(84, 720, 13, 0),
QT_MOC_LITERAL(85, 734, 5, 0),
QT_MOC_LITERAL(86, 740, 7, 0),
QT_MOC_LITERAL(87, 748, 5, 0),
QT_MOC_LITERAL(88, 754, 8, 0),
QT_MOC_LITERAL(89, 763, 6, 0),
QT_MOC_LITERAL(90, 770, 21, 0)
    },
    "stdole::Font\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0"
    "argc\0argv\0SetBold\0Bold\0SetCharset\0Charset\0SetItalic\0Italic\0SetName\0Name\0"
    "SetSize\0Size\0SetStrikethrough\0Strikethrough\0SetUnderline\0Underline\0SetWeight\0"
    "Weight\0control\0LoadPictureConstants\0Default\0Monochrome\0VgaColor\0Color\0"
    "OLE_TRISTATE\0Unchecked\0Checked\0Gray\0stdole::StdFont\0Interface 0\0Font\0FontChanged\0"
    "PropertyName\0AddRefHfont\0hFont\0Clone\0QFont&\0ppfont\0IsEqual\0pfontOther\0"
    "ReleaseHfont\0SetRatio\0cyLogical\0cyHimetric\0int*\0stdole::Picture\0Render\0hdc\0"
    "x\0y\0cx\0cy\0xSrc\0ySrc\0cxSrc\0cySrc\0prcWBounds\0setHPal\0hPal\0Handle\0Height\0Type\0"
    "Width\0stdole::StdPicture\0Picture\0Attributes\0CurDC\0KeepOriginalFormat\0"
    "PictureChanged\0SaveAsFile\0pstm\0fSaveMemCopy\0int&\0pcbSize\0SelectPicture\0hdcIn\0"
    "phdcOut\0int*&\0phbmpOut\0SetHdc\0SetKeepOriginalFormat\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_stdole__Font[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    11, 14, // methods
    9, 112, // properties
    2, 139, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 69, 2, 5,
    7, 1, 78, 2, 5,
    9, 3, 81, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 88, 2, 9,
    14, 1, 91, 2, 9,
    16, 1, 94, 2, 9,
    18, 1, 97, 2, 9,
    20, 1, 100, 2, 9,
    22, 1, 103, 2, 9,
    24, 1, 106, 2, 9,
    26, 1, 109, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 13,
    QMetaType::Void, QMetaType::Int, 15,
    QMetaType::Void, QMetaType::Bool, 17,
    QMetaType::Void, QMetaType::QString, 19,
    QMetaType::Void, QMetaType::LongLong, 21,
    QMetaType::Void, QMetaType::Bool, 23,
    QMetaType::Void, QMetaType::Bool, 25,
    QMetaType::Void, QMetaType::Int, 27,

 // properties: name, type, flags
    13, QMetaType::Bool, 0x01015003, 		 // bool Bold
    15, QMetaType::Int, 0x02015003, 		 // int Charset
    17, QMetaType::Bool, 0x01015003, 		 // bool Italic
    19, QMetaType::QString, 0x0a015003, 		 // QString Name
    21, QMetaType::LongLong, 0x04015003, 		 // qlonglong Size
    23, QMetaType::Bool, 0x01015003, 		 // bool Strikethrough
    25, QMetaType::Bool, 0x01015003, 		 // bool Underline
    27, QMetaType::Int, 0x02015003, 		 // int Weight
    28, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    29, 0x0, 4, 147, 
    34, 0x0, 3, 155, 

 // enum data: key, value
    30, uint(stdole::Default),
    31, uint(stdole::Monochrome),
    32, uint(stdole::VgaColor),
    33, uint(stdole::Color),
    35, uint(stdole::Unchecked),
    36, uint(stdole::Checked),
    37, uint(stdole::Gray),
    0 // eod
};

const QMetaObject Font::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_stdole__Font, 0, 0, 0 }
};

void *Font::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "stdole::Font"))
        return static_cast<void*>(const_cast<Font*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_stdole__StdFont[] = {

 // content:
    7, // revision
    38,  // classname
    1, 14, // classinfo
    26, 16, // methods
    9, 218, // properties
    2, 245, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    39, 40, 

// signal: name, argc, parameters, tag, flags
    41, 1, 146, 2, 5,
    1, 4, 149, 2, 5,
    7, 1, 158, 2, 5,
    9, 3, 161, 2, 5,

// slot: name, argc, parameters, tag, flags
    43, 1, 168, 2, 9,
    13, 0, 171, 2, 9,
    15, 0, 172, 2, 9,
    45, 1, 173, 2, 9,
    48, 1, 176, 2, 9,
    17, 0, 179, 2, 9,
    19, 0, 180, 2, 9,
    50, 1, 181, 2, 9,
    12, 1, 184, 2, 9,
    14, 1, 187, 2, 9,
    16, 1, 190, 2, 9,
    18, 1, 193, 2, 9,
    51, 2, 196, 2, 9,
    20, 1, 201, 2, 9,
    22, 1, 204, 2, 9,
    24, 1, 207, 2, 9,
    26, 1, 210, 2, 9,
    21, 0, 213, 2, 9,
    23, 0, 214, 2, 9,
    25, 0, 215, 2, 9,
    27, 0, 216, 2, 9,
    44, 0, 217, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QString, 42,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 44,
    QMetaType::Bool,
    QMetaType::Int,
    QMetaType::Void, 0x80000000 | 46, 47,
    QMetaType::Void, QMetaType::QFont, 49,
    QMetaType::Bool,
    QMetaType::QString,
    QMetaType::Void, QMetaType::Int, 44,
    QMetaType::Void, QMetaType::Bool, 13,
    QMetaType::Void, QMetaType::Int, 15,
    QMetaType::Void, QMetaType::Bool, 17,
    QMetaType::Void, QMetaType::QString, 19,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 52, 53,
    QMetaType::Void, QMetaType::LongLong, 21,
    QMetaType::Void, QMetaType::Bool, 23,
    QMetaType::Void, QMetaType::Bool, 25,
    QMetaType::Void, QMetaType::Int, 27,
    QMetaType::LongLong,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Int,
    0x80000000 | 54,

 // properties: name, type, flags
    13, QMetaType::Bool, 0x01015003, 		 // bool Bold
    15, QMetaType::Int, 0x02015003, 		 // int Charset
    17, QMetaType::Bool, 0x01015003, 		 // bool Italic
    19, QMetaType::QString, 0x0a015003, 		 // QString Name
    21, QMetaType::LongLong, 0x04015003, 		 // qlonglong Size
    23, QMetaType::Bool, 0x01015003, 		 // bool Strikethrough
    25, QMetaType::Bool, 0x01015003, 		 // bool Underline
    27, QMetaType::Int, 0x02015003, 		 // int Weight
    44, 0x80000000 | 54, 0x00005001, 		 // int* hFont

 // enums: name, flags, count, data
    29, 0x0, 4, 253, 
    34, 0x0, 3, 261, 

 // enum data: key, value
    30, uint(stdole::Default),
    31, uint(stdole::Monochrome),
    32, uint(stdole::VgaColor),
    33, uint(stdole::Color),
    35, uint(stdole::Unchecked),
    36, uint(stdole::Checked),
    37, uint(stdole::Gray),
    0 // eod
};

const QMetaObject StdFont::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_stdole__StdFont, 0, 0, 0 }
};

void *StdFont::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "stdole::StdFont"))
        return static_cast<void*>(const_cast<StdFont*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_stdole__Picture[] = {

 // content:
    7, // revision
    55,  // classname
    0, 0, // classinfo
    5, 14, // methods
    6, 82, // properties
    2, 100, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 39, 2, 5,
    7, 1, 48, 2, 5,
    9, 3, 51, 2, 5,

// slot: name, argc, parameters, tag, flags
    56, 10, 58, 2, 9,
    67, 1, 79, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::VoidStar, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
    QMetaType::Void, QMetaType::Int, 68,

 // properties: name, type, flags
    69, QMetaType::Int, 0x02005001, 		 // int Handle
    70, QMetaType::Int, 0x02005001, 		 // int Height
    71, QMetaType::Int, 0x02005001, 		 // int Type
    72, QMetaType::Int, 0x02005001, 		 // int Width
    28, QMetaType::QString, 0x0a055003, 		 // QString control
    68, QMetaType::Int, 0x02015003, 		 // int hPal

 // enums: name, flags, count, data
    29, 0x0, 4, 108, 
    34, 0x0, 3, 116, 

 // enum data: key, value
    30, uint(stdole::Default),
    31, uint(stdole::Monochrome),
    32, uint(stdole::VgaColor),
    33, uint(stdole::Color),
    35, uint(stdole::Unchecked),
    36, uint(stdole::Checked),
    37, uint(stdole::Gray),
    0 // eod
};

const QMetaObject Picture::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_stdole__Picture, 0, 0, 0 }
};

void *Picture::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "stdole::Picture"))
        return static_cast<void*>(const_cast<Picture*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_stdole__StdPicture[] = {

 // content:
    7, // revision
    73,  // classname
    1, 14, // classinfo
    18, 16, // methods
    8, 178, // properties
    2, 202, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    39, 74, 

// signal: name, argc, parameters, tag, flags
    1, 4, 106, 2, 5,
    7, 1, 115, 2, 5,
    9, 3, 118, 2, 5,

// slot: name, argc, parameters, tag, flags
    75, 0, 125, 2, 9,
    76, 0, 126, 2, 9,
    69, 0, 127, 2, 9,
    70, 0, 128, 2, 9,
    77, 0, 129, 2, 9,
    78, 0, 130, 2, 9,
    56, 10, 131, 2, 9,
    79, 3, 152, 2, 9,
    84, 3, 159, 2, 9,
    89, 1, 166, 2, 9,
    90, 1, 169, 2, 9,
    71, 0, 172, 2, 9,
    72, 0, 173, 2, 9,
    68, 0, 174, 2, 9,
    67, 1, 175, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int,
    QMetaType::Int,
    0x80000000 | 54,
    0x80000000 | 54,
    QMetaType::Bool,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::VoidStar, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
    QMetaType::Void, QMetaType::VoidStar, QMetaType::Bool, 0x80000000 | 82, 80, 81, 83,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 82, 0x80000000 | 87, 85, 86, 88,
    QMetaType::Void, QMetaType::Int, 57,
    QMetaType::Void, QMetaType::Bool, 77,
    QMetaType::Int,
    0x80000000 | 54,
    0x80000000 | 54,
    QMetaType::Void, QMetaType::Int, 68,

 // properties: name, type, flags
    75, QMetaType::Int, 0x02005001, 		 // int Attributes
    76, QMetaType::Int, 0x02005001, 		 // int CurDC
    69, 0x80000000 | 54, 0x00005001, 		 // int* Handle
    70, 0x80000000 | 54, 0x00005001, 		 // int* Height
    77, QMetaType::Bool, 0x01015003, 		 // bool KeepOriginalFormat
    71, QMetaType::Int, 0x02005001, 		 // int Type
    72, 0x80000000 | 54, 0x00005001, 		 // int* Width
    68, QMetaType::Int, 0x02015003, 		 // int hPal

 // enums: name, flags, count, data
    29, 0x0, 4, 210, 
    34, 0x0, 3, 218, 

 // enum data: key, value
    30, uint(stdole::Default),
    31, uint(stdole::Monochrome),
    32, uint(stdole::VgaColor),
    33, uint(stdole::Color),
    35, uint(stdole::Unchecked),
    36, uint(stdole::Checked),
    37, uint(stdole::Gray),
    0 // eod
};

const QMetaObject StdPicture::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_stdole__StdPicture, 0, 0, 0 }
};

void *StdPicture::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "stdole::StdPicture"))
        return static_cast<void*>(const_cast<StdPicture*>(this));
    return QAxObject::qt_metacast(_clname);
}

