/****************************************************************************
**
** Metadata for VBA generated by dumpcpp from type library
** C:\Windows\system32\msvbvm60.dll
**
****************************************************************************/

#define QAX_DUMPCPP_VBA_NOINLINES
#include "vba.h"

using namespace VBA;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[171];
    char stringdata0[1962];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 15, 0),
QT_MOC_LITERAL(1, 16, 9, 0),
QT_MOC_LITERAL(2, 26, 0, 0),
QT_MOC_LITERAL(3, 27, 4, 0),
QT_MOC_LITERAL(4, 32, 6, 0),
QT_MOC_LITERAL(5, 39, 4, 0),
QT_MOC_LITERAL(6, 44, 4, 0),
QT_MOC_LITERAL(7, 49, 15, 0),
QT_MOC_LITERAL(8, 65, 4, 0),
QT_MOC_LITERAL(9, 70, 6, 0),
QT_MOC_LITERAL(10, 77, 4, 0),
QT_MOC_LITERAL(11, 82, 4, 0),
QT_MOC_LITERAL(12, 87, 5, 0),
QT_MOC_LITERAL(13, 93, 5, 0),
QT_MOC_LITERAL(14, 99, 6, 0),
QT_MOC_LITERAL(15, 106, 9, 0),
QT_MOC_LITERAL(16, 116, 6, 0),
QT_MOC_LITERAL(17, 123, 11, 0),
QT_MOC_LITERAL(18, 135, 8, 0),
QT_MOC_LITERAL(19, 144, 11, 0),
QT_MOC_LITERAL(20, 156, 14, 0),
QT_MOC_LITERAL(21, 171, 14, 0),
QT_MOC_LITERAL(22, 186, 11, 0),
QT_MOC_LITERAL(23, 198, 9, 0),
QT_MOC_LITERAL(24, 208, 9, 0),
QT_MOC_LITERAL(25, 218, 12, 0),
QT_MOC_LITERAL(26, 231, 7, 0),
QT_MOC_LITERAL(27, 239, 13, 0),
QT_MOC_LITERAL(28, 253, 6, 0),
QT_MOC_LITERAL(29, 260, 13, 0),
QT_MOC_LITERAL(30, 274, 16, 0),
QT_MOC_LITERAL(31, 291, 16, 0),
QT_MOC_LITERAL(32, 308, 15, 0),
QT_MOC_LITERAL(33, 324, 18, 0),
QT_MOC_LITERAL(34, 343, 10, 0),
QT_MOC_LITERAL(35, 354, 9, 0),
QT_MOC_LITERAL(36, 364, 10, 0),
QT_MOC_LITERAL(37, 375, 10, 0),
QT_MOC_LITERAL(38, 386, 8, 0),
QT_MOC_LITERAL(39, 395, 5, 0),
QT_MOC_LITERAL(40, 401, 5, 0),
QT_MOC_LITERAL(41, 407, 5, 0),
QT_MOC_LITERAL(42, 413, 15, 0),
QT_MOC_LITERAL(43, 429, 15, 0),
QT_MOC_LITERAL(44, 445, 13, 0),
QT_MOC_LITERAL(45, 459, 17, 0),
QT_MOC_LITERAL(46, 477, 16, 0),
QT_MOC_LITERAL(47, 494, 13, 0),
QT_MOC_LITERAL(48, 508, 10, 0),
QT_MOC_LITERAL(49, 519, 11, 0),
QT_MOC_LITERAL(50, 531, 10, 0),
QT_MOC_LITERAL(51, 542, 11, 0),
QT_MOC_LITERAL(52, 554, 11, 0),
QT_MOC_LITERAL(53, 566, 20, 0),
QT_MOC_LITERAL(54, 587, 8, 0),
QT_MOC_LITERAL(55, 596, 8, 0),
QT_MOC_LITERAL(56, 605, 9, 0),
QT_MOC_LITERAL(57, 615, 11, 0),
QT_MOC_LITERAL(58, 627, 10, 0),
QT_MOC_LITERAL(59, 638, 8, 0),
QT_MOC_LITERAL(60, 647, 10, 0),
QT_MOC_LITERAL(61, 658, 15, 0),
QT_MOC_LITERAL(62, 674, 8, 0),
QT_MOC_LITERAL(63, 683, 10, 0),
QT_MOC_LITERAL(64, 694, 8, 0),
QT_MOC_LITERAL(65, 703, 8, 0),
QT_MOC_LITERAL(66, 712, 8, 0),
QT_MOC_LITERAL(67, 721, 11, 0),
QT_MOC_LITERAL(68, 733, 9, 0),
QT_MOC_LITERAL(69, 743, 7, 0),
QT_MOC_LITERAL(70, 751, 17, 0),
QT_MOC_LITERAL(71, 769, 11, 0),
QT_MOC_LITERAL(72, 781, 11, 0),
QT_MOC_LITERAL(73, 793, 15, 0),
QT_MOC_LITERAL(74, 809, 15, 0),
QT_MOC_LITERAL(75, 825, 11, 0),
QT_MOC_LITERAL(76, 837, 9, 0),
QT_MOC_LITERAL(77, 847, 18, 0),
QT_MOC_LITERAL(78, 866, 7, 0),
QT_MOC_LITERAL(79, 874, 11, 0),
QT_MOC_LITERAL(80, 886, 8, 0),
QT_MOC_LITERAL(81, 895, 12, 0),
QT_MOC_LITERAL(82, 908, 12, 0),
QT_MOC_LITERAL(83, 921, 16, 0),
QT_MOC_LITERAL(84, 938, 13, 0),
QT_MOC_LITERAL(85, 952, 17, 0),
QT_MOC_LITERAL(86, 970, 16, 0),
QT_MOC_LITERAL(87, 987, 17, 0),
QT_MOC_LITERAL(88, 1005, 16, 0),
QT_MOC_LITERAL(89, 1022, 21, 0),
QT_MOC_LITERAL(90, 1044, 13, 0),
QT_MOC_LITERAL(91, 1058, 18, 0),
QT_MOC_LITERAL(92, 1077, 13, 0),
QT_MOC_LITERAL(93, 1091, 14, 0),
QT_MOC_LITERAL(94, 1106, 19, 0),
QT_MOC_LITERAL(95, 1126, 15, 0),
QT_MOC_LITERAL(96, 1142, 14, 0),
QT_MOC_LITERAL(97, 1157, 4, 0),
QT_MOC_LITERAL(98, 1162, 8, 0),
QT_MOC_LITERAL(99, 1171, 7, 0),
QT_MOC_LITERAL(100, 1179, 7, 0),
QT_MOC_LITERAL(101, 1187, 8, 0),
QT_MOC_LITERAL(102, 1196, 5, 0),
QT_MOC_LITERAL(103, 1202, 4, 0),
QT_MOC_LITERAL(104, 1207, 13, 0),
QT_MOC_LITERAL(105, 1221, 8, 0),
QT_MOC_LITERAL(106, 1230, 10, 0),
QT_MOC_LITERAL(107, 1241, 18, 0),
QT_MOC_LITERAL(108, 1260, 13, 0),
QT_MOC_LITERAL(109, 1274, 7, 0),
QT_MOC_LITERAL(110, 1282, 13, 0),
QT_MOC_LITERAL(111, 1296, 10, 0),
QT_MOC_LITERAL(112, 1307, 10, 0),
QT_MOC_LITERAL(113, 1318, 13, 0),
QT_MOC_LITERAL(114, 1332, 13, 0),
QT_MOC_LITERAL(115, 1346, 16, 0),
QT_MOC_LITERAL(116, 1363, 16, 0),
QT_MOC_LITERAL(117, 1380, 16, 0),
QT_MOC_LITERAL(118, 1397, 16, 0),
QT_MOC_LITERAL(119, 1414, 18, 0),
QT_MOC_LITERAL(120, 1433, 13, 0),
QT_MOC_LITERAL(121, 1447, 18, 0),
QT_MOC_LITERAL(122, 1466, 13, 0),
QT_MOC_LITERAL(123, 1480, 18, 0),
QT_MOC_LITERAL(124, 1499, 21, 0),
QT_MOC_LITERAL(125, 1521, 9, 0),
QT_MOC_LITERAL(126, 1531, 11, 0),
QT_MOC_LITERAL(127, 1543, 11, 0),
QT_MOC_LITERAL(128, 1555, 12, 0),
QT_MOC_LITERAL(129, 1568, 6, 0),
QT_MOC_LITERAL(130, 1575, 8, 0),
QT_MOC_LITERAL(131, 1584, 10, 0),
QT_MOC_LITERAL(132, 1595, 10, 0),
QT_MOC_LITERAL(133, 1606, 9, 0),
QT_MOC_LITERAL(134, 1616, 13, 0),
QT_MOC_LITERAL(135, 1630, 10, 0),
QT_MOC_LITERAL(136, 1641, 12, 0),
QT_MOC_LITERAL(137, 1654, 6, 0),
QT_MOC_LITERAL(138, 1661, 7, 0),
QT_MOC_LITERAL(139, 1669, 9, 0),
QT_MOC_LITERAL(140, 1679, 7, 0),
QT_MOC_LITERAL(141, 1687, 6, 0),
QT_MOC_LITERAL(142, 1694, 9, 0),
QT_MOC_LITERAL(143, 1704, 6, 0),
QT_MOC_LITERAL(144, 1711, 8, 0),
QT_MOC_LITERAL(145, 1720, 8, 0),
QT_MOC_LITERAL(146, 1729, 10, 0),
QT_MOC_LITERAL(147, 1740, 6, 0),
QT_MOC_LITERAL(148, 1747, 8, 0),
QT_MOC_LITERAL(149, 1756, 8, 0),
QT_MOC_LITERAL(150, 1765, 7, 0),
QT_MOC_LITERAL(151, 1773, 9, 0),
QT_MOC_LITERAL(152, 1783, 9, 0),
QT_MOC_LITERAL(153, 1793, 12, 0),
QT_MOC_LITERAL(154, 1806, 9, 0),
QT_MOC_LITERAL(155, 1816, 6, 0),
QT_MOC_LITERAL(156, 1823, 17, 0),
QT_MOC_LITERAL(157, 1841, 7, 0),
QT_MOC_LITERAL(158, 1849, 14, 0),
QT_MOC_LITERAL(159, 1864, 16, 0),
QT_MOC_LITERAL(160, 1881, 3, 0),
QT_MOC_LITERAL(161, 1885, 4, 0),
QT_MOC_LITERAL(162, 1890, 3, 0),
QT_MOC_LITERAL(163, 1894, 6, 0),
QT_MOC_LITERAL(164, 1901, 5, 0),
QT_MOC_LITERAL(165, 1907, 5, 0),
QT_MOC_LITERAL(166, 1913, 5, 0),
QT_MOC_LITERAL(167, 1919, 6, 0),
QT_MOC_LITERAL(168, 1926, 8, 0),
QT_MOC_LITERAL(169, 1935, 9, 0),
QT_MOC_LITERAL(170, 1945, 15, 0)
    },
    "VBA::_ErrObject\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0"
    "argc\0argv\0Clear\0Raise\0Number\0QVariant&\0Source\0Description\0HelpFile\0HelpContext\0"
    "SetDescription\0SetHelpContext\0SetHelpFile\0SetNumber\0SetSource\0LastDllError\0"
    "control\0VbAppWinStyle\0vbHide\0vbNormalFocus\0vbMinimizedFocus\0vbMaximizedFocus\0"
    "vbNormalNoFocus\0vbMinimizedNoFocus\0VbCalendar\0vbCalGreg\0vbCalHijri\0VbCallType\0"
    "VbMethod\0VbGet\0VbLet\0VbSet\0VbCompareMethod\0vbBinaryCompare\0vbTextCompare\0"
    "vbDatabaseCompare\0VbDateTimeFormat\0vbGeneralDate\0vbLongDate\0vbShortDate\0"
    "vbLongTime\0vbShortTime\0VbDayOfWeek\0vbUseSystemDayOfWeek\0vbSunday\0vbMonday\0"
    "vbTuesday\0vbWednesday\0vbThursday\0vbFriday\0vbSaturday\0VbFileAttribute\0vbNormal\0"
    "vbReadOnly\0vbHidden\0vbSystem\0vbVolume\0vbDirectory\0vbArchive\0vbAlias\0"
    "VbFirstWeekOfYear\0vbUseSystem\0vbFirstJan1\0vbFirstFourDays\0vbFirstFullWeek\0"
    "VbIMEStatus\0vbIMENoOp\0vbIMEModeNoControl\0vbIMEOn\0vbIMEModeOn\0vbIMEOff\0"
    "vbIMEModeOff\0vbIMEDisable\0vbIMEModeDisable\0vbIMEHiragana\0vbIMEModeHiragana\0"
    "vbIMEKatakanaDbl\0vbIMEModeKatakana\0vbIMEKatakanaSng\0vbIMEModeKatakanaHalf\0"
    "vbIMEAlphaDbl\0vbIMEModeAlphaFull\0vbIMEAlphaSng\0vbIMEModeAlpha\0vbIMEModeHangulFull\0"
    "vbIMEModeHangul\0VbMsgBoxResult\0vbOK\0vbCancel\0vbAbort\0vbRetry\0vbIgnore\0vbYes\0"
    "vbNo\0VbMsgBoxStyle\0vbOKOnly\0vbOKCancel\0vbAbortRetryIgnore\0vbYesNoCancel\0"
    "vbYesNo\0vbRetryCancel\0vbCritical\0vbQuestion\0vbExclamation\0vbInformation\0"
    "vbDefaultButton1\0vbDefaultButton2\0vbDefaultButton3\0vbDefaultButton4\0"
    "vbApplicationModal\0vbSystemModal\0vbMsgBoxHelpButton\0vbMsgBoxRight\0"
    "vbMsgBoxRtlReading\0vbMsgBoxSetForeground\0VbStrConv\0vbUpperCase\0vbLowerCase\0"
    "vbProperCase\0vbWide\0vbNarrow\0vbKatakana\0vbHiragana\0vbUnicode\0vbFromUnicode\0"
    "VbTriState\0vbUseDefault\0vbTrue\0vbFalse\0VbVarType\0vbEmpty\0vbNull\0vbInteger\0"
    "vbLong\0vbSingle\0vbDouble\0vbCurrency\0vbDate\0vbString\0vbObject\0vbError\0vbBoolean\0"
    "vbVariant\0vbDataObject\0vbDecimal\0vbByte\0vbUserDefinedType\0vbArray\0VBA::ErrObject\0"
    "VBA::_Collection\0Add\0Item\0Key\0Before\0After\0Count\0Index\0Remove\0_NewEnum\0"
    "IUnknown*\0VBA::Collection\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VBA___ErrObject[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    14, 14, // methods
    7, 154, // properties
    14, 175, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 84, 2, 5,
    7, 1, 93, 2, 5,
    9, 3, 96, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 103, 2, 9,
    13, 1, 104, 2, 11,
    13, 2, 107, 2, 11,
    13, 3, 112, 2, 11,
    13, 4, 119, 2, 11,
    13, 5, 128, 2, 9,
    20, 1, 139, 2, 9,
    21, 1, 142, 2, 9,
    22, 1, 145, 2, 9,
    23, 1, 148, 2, 9,
    24, 1, 151, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 15, 14, 16,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 15, 0x80000000 | 15, 14, 16, 17,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 14, 16, 17, 18,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 14, 16, 17, 18, 19,
    QMetaType::Void, QMetaType::QString, 17,
    QMetaType::Void, QMetaType::Int, 19,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::QString, 16,

 // properties: name, type, flags
    17, QMetaType::QString, 0x0a015003, 		 // QString Description
    19, QMetaType::Int, 0x02015003, 		 // int HelpContext
    18, QMetaType::QString, 0x0a015003, 		 // QString HelpFile
    25, QMetaType::Int, 0x02005001, 		 // int LastDllError
    14, QMetaType::Int, 0x02015003, 		 // int Number
    16, QMetaType::QString, 0x0a015003, 		 // QString Source
    26, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    27, 0x0, 6, 231, 
    34, 0x0, 2, 243, 
    37, 0x0, 4, 247, 
    42, 0x0, 3, 255, 
    46, 0x0, 5, 261, 
    52, 0x0, 8, 271, 
    61, 0x0, 8, 287, 
    70, 0x0, 4, 303, 
    75, 0x0, 20, 311, 
    96, 0x0, 7, 351, 
    104, 0x0, 20, 365, 
    125, 0x0, 9, 405, 
    135, 0x0, 3, 423, 
    139, 0x0, 18, 429, 

 // enum data: key, value
    28, uint(VBA::vbHide),
    29, uint(VBA::vbNormalFocus),
    30, uint(VBA::vbMinimizedFocus),
    31, uint(VBA::vbMaximizedFocus),
    32, uint(VBA::vbNormalNoFocus),
    33, uint(VBA::vbMinimizedNoFocus),
    35, uint(VBA::vbCalGreg),
    36, uint(VBA::vbCalHijri),
    38, uint(VBA::VbMethod),
    39, uint(VBA::VbGet),
    40, uint(VBA::VbLet),
    41, uint(VBA::VbSet),
    43, uint(VBA::vbBinaryCompare),
    44, uint(VBA::vbTextCompare),
    45, uint(VBA::vbDatabaseCompare),
    47, uint(VBA::vbGeneralDate),
    48, uint(VBA::vbLongDate),
    49, uint(VBA::vbShortDate),
    50, uint(VBA::vbLongTime),
    51, uint(VBA::vbShortTime),
    53, uint(VBA::vbUseSystemDayOfWeek),
    54, uint(VBA::vbSunday),
    55, uint(VBA::vbMonday),
    56, uint(VBA::vbTuesday),
    57, uint(VBA::vbWednesday),
    58, uint(VBA::vbThursday),
    59, uint(VBA::vbFriday),
    60, uint(VBA::vbSaturday),
    62, uint(VBA::vbNormal),
    63, uint(VBA::vbReadOnly),
    64, uint(VBA::vbHidden),
    65, uint(VBA::vbSystem),
    66, uint(VBA::vbVolume),
    67, uint(VBA::vbDirectory),
    68, uint(VBA::vbArchive),
    69, uint(VBA::vbAlias),
    71, uint(VBA::vbUseSystem),
    72, uint(VBA::vbFirstJan1),
    73, uint(VBA::vbFirstFourDays),
    74, uint(VBA::vbFirstFullWeek),
    76, uint(VBA::vbIMENoOp),
    77, uint(VBA::vbIMEModeNoControl),
    78, uint(VBA::vbIMEOn),
    79, uint(VBA::vbIMEModeOn),
    80, uint(VBA::vbIMEOff),
    81, uint(VBA::vbIMEModeOff),
    82, uint(VBA::vbIMEDisable),
    83, uint(VBA::vbIMEModeDisable),
    84, uint(VBA::vbIMEHiragana),
    85, uint(VBA::vbIMEModeHiragana),
    86, uint(VBA::vbIMEKatakanaDbl),
    87, uint(VBA::vbIMEModeKatakana),
    88, uint(VBA::vbIMEKatakanaSng),
    89, uint(VBA::vbIMEModeKatakanaHalf),
    90, uint(VBA::vbIMEAlphaDbl),
    91, uint(VBA::vbIMEModeAlphaFull),
    92, uint(VBA::vbIMEAlphaSng),
    93, uint(VBA::vbIMEModeAlpha),
    94, uint(VBA::vbIMEModeHangulFull),
    95, uint(VBA::vbIMEModeHangul),
    97, uint(VBA::vbOK),
    98, uint(VBA::vbCancel),
    99, uint(VBA::vbAbort),
    100, uint(VBA::vbRetry),
    101, uint(VBA::vbIgnore),
    102, uint(VBA::vbYes),
    103, uint(VBA::vbNo),
    105, uint(VBA::vbOKOnly),
    106, uint(VBA::vbOKCancel),
    107, uint(VBA::vbAbortRetryIgnore),
    108, uint(VBA::vbYesNoCancel),
    109, uint(VBA::vbYesNo),
    110, uint(VBA::vbRetryCancel),
    111, uint(VBA::vbCritical),
    112, uint(VBA::vbQuestion),
    113, uint(VBA::vbExclamation),
    114, uint(VBA::vbInformation),
    115, uint(VBA::vbDefaultButton1),
    116, uint(VBA::vbDefaultButton2),
    117, uint(VBA::vbDefaultButton3),
    118, uint(VBA::vbDefaultButton4),
    119, uint(VBA::vbApplicationModal),
    120, uint(VBA::vbSystemModal),
    121, uint(VBA::vbMsgBoxHelpButton),
    122, uint(VBA::vbMsgBoxRight),
    123, uint(VBA::vbMsgBoxRtlReading),
    124, uint(VBA::vbMsgBoxSetForeground),
    126, uint(VBA::vbUpperCase),
    127, uint(VBA::vbLowerCase),
    128, uint(VBA::vbProperCase),
    129, uint(VBA::vbWide),
    130, uint(VBA::vbNarrow),
    131, uint(VBA::vbKatakana),
    132, uint(VBA::vbHiragana),
    133, uint(VBA::vbUnicode),
    134, uint(VBA::vbFromUnicode),
    136, uint(VBA::vbUseDefault),
    137, uint(VBA::vbTrue),
    138, uint(VBA::vbFalse),
    140, uint(VBA::vbEmpty),
    141, uint(VBA::vbNull),
    142, uint(VBA::vbInteger),
    143, uint(VBA::vbLong),
    144, uint(VBA::vbSingle),
    145, uint(VBA::vbDouble),
    146, uint(VBA::vbCurrency),
    147, uint(VBA::vbDate),
    148, uint(VBA::vbString),
    149, uint(VBA::vbObject),
    150, uint(VBA::vbError),
    151, uint(VBA::vbBoolean),
    152, uint(VBA::vbVariant),
    153, uint(VBA::vbDataObject),
    154, uint(VBA::vbDecimal),
    155, uint(VBA::vbByte),
    156, uint(VBA::vbUserDefinedType),
    157, uint(VBA::vbArray),
    0 // eod
};

const QMetaObject _ErrObject::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VBA___ErrObject, 0, 0, 0 }
};

void *_ErrObject::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VBA::_ErrObject"))
        return static_cast<void*>(const_cast<_ErrObject*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_VBA__ErrObject[] = {

 // content:
    7, // revision
    158,  // classname
    0, 0, // classinfo
    14, 14, // methods
    6, 154, // properties
    14, 172, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 84, 2, 5,
    7, 1, 93, 2, 5,
    9, 3, 96, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 103, 2, 9,
    13, 1, 104, 2, 11,
    13, 2, 107, 2, 11,
    13, 3, 112, 2, 11,
    13, 4, 119, 2, 11,
    13, 5, 128, 2, 9,
    20, 1, 139, 2, 9,
    21, 1, 142, 2, 9,
    22, 1, 145, 2, 9,
    23, 1, 148, 2, 9,
    24, 1, 151, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 15, 14, 16,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 15, 0x80000000 | 15, 14, 16, 17,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 14, 16, 17, 18,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 14, 16, 17, 18, 19,
    QMetaType::Void, QMetaType::QString, 17,
    QMetaType::Void, QMetaType::Int, 19,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::QString, 16,

 // properties: name, type, flags
    17, QMetaType::QString, 0x0a015003, 		 // QString Description
    19, QMetaType::Int, 0x02015003, 		 // int HelpContext
    18, QMetaType::QString, 0x0a015003, 		 // QString HelpFile
    25, QMetaType::Int, 0x02005001, 		 // int LastDllError
    14, QMetaType::Int, 0x02015003, 		 // int Number
    16, QMetaType::QString, 0x0a015003, 		 // QString Source

 // enums: name, flags, count, data
    27, 0x0, 6, 228, 
    34, 0x0, 2, 240, 
    37, 0x0, 4, 244, 
    42, 0x0, 3, 252, 
    46, 0x0, 5, 258, 
    52, 0x0, 8, 268, 
    61, 0x0, 8, 284, 
    70, 0x0, 4, 300, 
    75, 0x0, 20, 308, 
    96, 0x0, 7, 348, 
    104, 0x0, 20, 362, 
    125, 0x0, 9, 402, 
    135, 0x0, 3, 420, 
    139, 0x0, 18, 426, 

 // enum data: key, value
    28, uint(VBA::vbHide),
    29, uint(VBA::vbNormalFocus),
    30, uint(VBA::vbMinimizedFocus),
    31, uint(VBA::vbMaximizedFocus),
    32, uint(VBA::vbNormalNoFocus),
    33, uint(VBA::vbMinimizedNoFocus),
    35, uint(VBA::vbCalGreg),
    36, uint(VBA::vbCalHijri),
    38, uint(VBA::VbMethod),
    39, uint(VBA::VbGet),
    40, uint(VBA::VbLet),
    41, uint(VBA::VbSet),
    43, uint(VBA::vbBinaryCompare),
    44, uint(VBA::vbTextCompare),
    45, uint(VBA::vbDatabaseCompare),
    47, uint(VBA::vbGeneralDate),
    48, uint(VBA::vbLongDate),
    49, uint(VBA::vbShortDate),
    50, uint(VBA::vbLongTime),
    51, uint(VBA::vbShortTime),
    53, uint(VBA::vbUseSystemDayOfWeek),
    54, uint(VBA::vbSunday),
    55, uint(VBA::vbMonday),
    56, uint(VBA::vbTuesday),
    57, uint(VBA::vbWednesday),
    58, uint(VBA::vbThursday),
    59, uint(VBA::vbFriday),
    60, uint(VBA::vbSaturday),
    62, uint(VBA::vbNormal),
    63, uint(VBA::vbReadOnly),
    64, uint(VBA::vbHidden),
    65, uint(VBA::vbSystem),
    66, uint(VBA::vbVolume),
    67, uint(VBA::vbDirectory),
    68, uint(VBA::vbArchive),
    69, uint(VBA::vbAlias),
    71, uint(VBA::vbUseSystem),
    72, uint(VBA::vbFirstJan1),
    73, uint(VBA::vbFirstFourDays),
    74, uint(VBA::vbFirstFullWeek),
    76, uint(VBA::vbIMENoOp),
    77, uint(VBA::vbIMEModeNoControl),
    78, uint(VBA::vbIMEOn),
    79, uint(VBA::vbIMEModeOn),
    80, uint(VBA::vbIMEOff),
    81, uint(VBA::vbIMEModeOff),
    82, uint(VBA::vbIMEDisable),
    83, uint(VBA::vbIMEModeDisable),
    84, uint(VBA::vbIMEHiragana),
    85, uint(VBA::vbIMEModeHiragana),
    86, uint(VBA::vbIMEKatakanaDbl),
    87, uint(VBA::vbIMEModeKatakana),
    88, uint(VBA::vbIMEKatakanaSng),
    89, uint(VBA::vbIMEModeKatakanaHalf),
    90, uint(VBA::vbIMEAlphaDbl),
    91, uint(VBA::vbIMEModeAlphaFull),
    92, uint(VBA::vbIMEAlphaSng),
    93, uint(VBA::vbIMEModeAlpha),
    94, uint(VBA::vbIMEModeHangulFull),
    95, uint(VBA::vbIMEModeHangul),
    97, uint(VBA::vbOK),
    98, uint(VBA::vbCancel),
    99, uint(VBA::vbAbort),
    100, uint(VBA::vbRetry),
    101, uint(VBA::vbIgnore),
    102, uint(VBA::vbYes),
    103, uint(VBA::vbNo),
    105, uint(VBA::vbOKOnly),
    106, uint(VBA::vbOKCancel),
    107, uint(VBA::vbAbortRetryIgnore),
    108, uint(VBA::vbYesNoCancel),
    109, uint(VBA::vbYesNo),
    110, uint(VBA::vbRetryCancel),
    111, uint(VBA::vbCritical),
    112, uint(VBA::vbQuestion),
    113, uint(VBA::vbExclamation),
    114, uint(VBA::vbInformation),
    115, uint(VBA::vbDefaultButton1),
    116, uint(VBA::vbDefaultButton2),
    117, uint(VBA::vbDefaultButton3),
    118, uint(VBA::vbDefaultButton4),
    119, uint(VBA::vbApplicationModal),
    120, uint(VBA::vbSystemModal),
    121, uint(VBA::vbMsgBoxHelpButton),
    122, uint(VBA::vbMsgBoxRight),
    123, uint(VBA::vbMsgBoxRtlReading),
    124, uint(VBA::vbMsgBoxSetForeground),
    126, uint(VBA::vbUpperCase),
    127, uint(VBA::vbLowerCase),
    128, uint(VBA::vbProperCase),
    129, uint(VBA::vbWide),
    130, uint(VBA::vbNarrow),
    131, uint(VBA::vbKatakana),
    132, uint(VBA::vbHiragana),
    133, uint(VBA::vbUnicode),
    134, uint(VBA::vbFromUnicode),
    136, uint(VBA::vbUseDefault),
    137, uint(VBA::vbTrue),
    138, uint(VBA::vbFalse),
    140, uint(VBA::vbEmpty),
    141, uint(VBA::vbNull),
    142, uint(VBA::vbInteger),
    143, uint(VBA::vbLong),
    144, uint(VBA::vbSingle),
    145, uint(VBA::vbDouble),
    146, uint(VBA::vbCurrency),
    147, uint(VBA::vbDate),
    148, uint(VBA::vbString),
    149, uint(VBA::vbObject),
    150, uint(VBA::vbError),
    151, uint(VBA::vbBoolean),
    152, uint(VBA::vbVariant),
    153, uint(VBA::vbDataObject),
    154, uint(VBA::vbDecimal),
    155, uint(VBA::vbByte),
    156, uint(VBA::vbUserDefinedType),
    157, uint(VBA::vbArray),
    0 // eod
};

const QMetaObject ErrObject::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VBA__ErrObject, 0, 0, 0 }
};

void *ErrObject::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VBA::ErrObject"))
        return static_cast<void*>(const_cast<ErrObject*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_VBA___Collection[] = {

 // content:
    7, // revision
    159,  // classname
    0, 0, // classinfo
    11, 14, // methods
    1, 120, // properties
    14, 123, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 69, 2, 5,
    7, 1, 78, 2, 5,
    9, 3, 81, 2, 5,

// slot: name, argc, parameters, tag, flags
    160, 1, 88, 2, 11,
    160, 2, 91, 2, 11,
    160, 3, 96, 2, 11,
    160, 4, 103, 2, 9,
    165, 0, 112, 2, 9,
    161, 1, 113, 2, 9,
    167, 1, 116, 2, 9,
    168, 0, 119, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, 0x80000000 | 15, 161,
    QMetaType::Void, 0x80000000 | 15, 0x80000000 | 15, 161, 162,
    QMetaType::Void, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 161, 162, 163,
    QMetaType::Void, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 161, 162, 163, 164,
    QMetaType::Int,
    QMetaType::QVariant, 0x80000000 | 15, 166,
    QMetaType::Void, 0x80000000 | 15, 166,
    0x80000000 | 169,

 // properties: name, type, flags
    26, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    27, 0x0, 6, 179, 
    34, 0x0, 2, 191, 
    37, 0x0, 4, 195, 
    42, 0x0, 3, 203, 
    46, 0x0, 5, 209, 
    52, 0x0, 8, 219, 
    61, 0x0, 8, 235, 
    70, 0x0, 4, 251, 
    75, 0x0, 20, 259, 
    96, 0x0, 7, 299, 
    104, 0x0, 20, 313, 
    125, 0x0, 9, 353, 
    135, 0x0, 3, 371, 
    139, 0x0, 18, 377, 

 // enum data: key, value
    28, uint(VBA::vbHide),
    29, uint(VBA::vbNormalFocus),
    30, uint(VBA::vbMinimizedFocus),
    31, uint(VBA::vbMaximizedFocus),
    32, uint(VBA::vbNormalNoFocus),
    33, uint(VBA::vbMinimizedNoFocus),
    35, uint(VBA::vbCalGreg),
    36, uint(VBA::vbCalHijri),
    38, uint(VBA::VbMethod),
    39, uint(VBA::VbGet),
    40, uint(VBA::VbLet),
    41, uint(VBA::VbSet),
    43, uint(VBA::vbBinaryCompare),
    44, uint(VBA::vbTextCompare),
    45, uint(VBA::vbDatabaseCompare),
    47, uint(VBA::vbGeneralDate),
    48, uint(VBA::vbLongDate),
    49, uint(VBA::vbShortDate),
    50, uint(VBA::vbLongTime),
    51, uint(VBA::vbShortTime),
    53, uint(VBA::vbUseSystemDayOfWeek),
    54, uint(VBA::vbSunday),
    55, uint(VBA::vbMonday),
    56, uint(VBA::vbTuesday),
    57, uint(VBA::vbWednesday),
    58, uint(VBA::vbThursday),
    59, uint(VBA::vbFriday),
    60, uint(VBA::vbSaturday),
    62, uint(VBA::vbNormal),
    63, uint(VBA::vbReadOnly),
    64, uint(VBA::vbHidden),
    65, uint(VBA::vbSystem),
    66, uint(VBA::vbVolume),
    67, uint(VBA::vbDirectory),
    68, uint(VBA::vbArchive),
    69, uint(VBA::vbAlias),
    71, uint(VBA::vbUseSystem),
    72, uint(VBA::vbFirstJan1),
    73, uint(VBA::vbFirstFourDays),
    74, uint(VBA::vbFirstFullWeek),
    76, uint(VBA::vbIMENoOp),
    77, uint(VBA::vbIMEModeNoControl),
    78, uint(VBA::vbIMEOn),
    79, uint(VBA::vbIMEModeOn),
    80, uint(VBA::vbIMEOff),
    81, uint(VBA::vbIMEModeOff),
    82, uint(VBA::vbIMEDisable),
    83, uint(VBA::vbIMEModeDisable),
    84, uint(VBA::vbIMEHiragana),
    85, uint(VBA::vbIMEModeHiragana),
    86, uint(VBA::vbIMEKatakanaDbl),
    87, uint(VBA::vbIMEModeKatakana),
    88, uint(VBA::vbIMEKatakanaSng),
    89, uint(VBA::vbIMEModeKatakanaHalf),
    90, uint(VBA::vbIMEAlphaDbl),
    91, uint(VBA::vbIMEModeAlphaFull),
    92, uint(VBA::vbIMEAlphaSng),
    93, uint(VBA::vbIMEModeAlpha),
    94, uint(VBA::vbIMEModeHangulFull),
    95, uint(VBA::vbIMEModeHangul),
    97, uint(VBA::vbOK),
    98, uint(VBA::vbCancel),
    99, uint(VBA::vbAbort),
    100, uint(VBA::vbRetry),
    101, uint(VBA::vbIgnore),
    102, uint(VBA::vbYes),
    103, uint(VBA::vbNo),
    105, uint(VBA::vbOKOnly),
    106, uint(VBA::vbOKCancel),
    107, uint(VBA::vbAbortRetryIgnore),
    108, uint(VBA::vbYesNoCancel),
    109, uint(VBA::vbYesNo),
    110, uint(VBA::vbRetryCancel),
    111, uint(VBA::vbCritical),
    112, uint(VBA::vbQuestion),
    113, uint(VBA::vbExclamation),
    114, uint(VBA::vbInformation),
    115, uint(VBA::vbDefaultButton1),
    116, uint(VBA::vbDefaultButton2),
    117, uint(VBA::vbDefaultButton3),
    118, uint(VBA::vbDefaultButton4),
    119, uint(VBA::vbApplicationModal),
    120, uint(VBA::vbSystemModal),
    121, uint(VBA::vbMsgBoxHelpButton),
    122, uint(VBA::vbMsgBoxRight),
    123, uint(VBA::vbMsgBoxRtlReading),
    124, uint(VBA::vbMsgBoxSetForeground),
    126, uint(VBA::vbUpperCase),
    127, uint(VBA::vbLowerCase),
    128, uint(VBA::vbProperCase),
    129, uint(VBA::vbWide),
    130, uint(VBA::vbNarrow),
    131, uint(VBA::vbKatakana),
    132, uint(VBA::vbHiragana),
    133, uint(VBA::vbUnicode),
    134, uint(VBA::vbFromUnicode),
    136, uint(VBA::vbUseDefault),
    137, uint(VBA::vbTrue),
    138, uint(VBA::vbFalse),
    140, uint(VBA::vbEmpty),
    141, uint(VBA::vbNull),
    142, uint(VBA::vbInteger),
    143, uint(VBA::vbLong),
    144, uint(VBA::vbSingle),
    145, uint(VBA::vbDouble),
    146, uint(VBA::vbCurrency),
    147, uint(VBA::vbDate),
    148, uint(VBA::vbString),
    149, uint(VBA::vbObject),
    150, uint(VBA::vbError),
    151, uint(VBA::vbBoolean),
    152, uint(VBA::vbVariant),
    153, uint(VBA::vbDataObject),
    154, uint(VBA::vbDecimal),
    155, uint(VBA::vbByte),
    156, uint(VBA::vbUserDefinedType),
    157, uint(VBA::vbArray),
    0 // eod
};

const QMetaObject _Collection::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VBA___Collection, 0, 0, 0 }
};

void *_Collection::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VBA::_Collection"))
        return static_cast<void*>(const_cast<_Collection*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_VBA__Collection[] = {

 // content:
    7, // revision
    170,  // classname
    0, 0, // classinfo
    11, 14, // methods
    0, 0, // properties
    14, 120, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 69, 2, 5,
    7, 1, 78, 2, 5,
    9, 3, 81, 2, 5,

// slot: name, argc, parameters, tag, flags
    160, 1, 88, 2, 11,
    160, 2, 91, 2, 11,
    160, 3, 96, 2, 11,
    160, 4, 103, 2, 9,
    165, 0, 112, 2, 9,
    161, 1, 113, 2, 9,
    167, 1, 116, 2, 9,
    168, 0, 119, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, 0x80000000 | 15, 161,
    QMetaType::Void, 0x80000000 | 15, 0x80000000 | 15, 161, 162,
    QMetaType::Void, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 161, 162, 163,
    QMetaType::Void, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 0x80000000 | 15, 161, 162, 163, 164,
    QMetaType::Int,
    QMetaType::QVariant, 0x80000000 | 15, 166,
    QMetaType::Void, 0x80000000 | 15, 166,
    0x80000000 | 169,

 // enums: name, flags, count, data
    27, 0x0, 6, 176, 
    34, 0x0, 2, 188, 
    37, 0x0, 4, 192, 
    42, 0x0, 3, 200, 
    46, 0x0, 5, 206, 
    52, 0x0, 8, 216, 
    61, 0x0, 8, 232, 
    70, 0x0, 4, 248, 
    75, 0x0, 20, 256, 
    96, 0x0, 7, 296, 
    104, 0x0, 20, 310, 
    125, 0x0, 9, 350, 
    135, 0x0, 3, 368, 
    139, 0x0, 18, 374, 

 // enum data: key, value
    28, uint(VBA::vbHide),
    29, uint(VBA::vbNormalFocus),
    30, uint(VBA::vbMinimizedFocus),
    31, uint(VBA::vbMaximizedFocus),
    32, uint(VBA::vbNormalNoFocus),
    33, uint(VBA::vbMinimizedNoFocus),
    35, uint(VBA::vbCalGreg),
    36, uint(VBA::vbCalHijri),
    38, uint(VBA::VbMethod),
    39, uint(VBA::VbGet),
    40, uint(VBA::VbLet),
    41, uint(VBA::VbSet),
    43, uint(VBA::vbBinaryCompare),
    44, uint(VBA::vbTextCompare),
    45, uint(VBA::vbDatabaseCompare),
    47, uint(VBA::vbGeneralDate),
    48, uint(VBA::vbLongDate),
    49, uint(VBA::vbShortDate),
    50, uint(VBA::vbLongTime),
    51, uint(VBA::vbShortTime),
    53, uint(VBA::vbUseSystemDayOfWeek),
    54, uint(VBA::vbSunday),
    55, uint(VBA::vbMonday),
    56, uint(VBA::vbTuesday),
    57, uint(VBA::vbWednesday),
    58, uint(VBA::vbThursday),
    59, uint(VBA::vbFriday),
    60, uint(VBA::vbSaturday),
    62, uint(VBA::vbNormal),
    63, uint(VBA::vbReadOnly),
    64, uint(VBA::vbHidden),
    65, uint(VBA::vbSystem),
    66, uint(VBA::vbVolume),
    67, uint(VBA::vbDirectory),
    68, uint(VBA::vbArchive),
    69, uint(VBA::vbAlias),
    71, uint(VBA::vbUseSystem),
    72, uint(VBA::vbFirstJan1),
    73, uint(VBA::vbFirstFourDays),
    74, uint(VBA::vbFirstFullWeek),
    76, uint(VBA::vbIMENoOp),
    77, uint(VBA::vbIMEModeNoControl),
    78, uint(VBA::vbIMEOn),
    79, uint(VBA::vbIMEModeOn),
    80, uint(VBA::vbIMEOff),
    81, uint(VBA::vbIMEModeOff),
    82, uint(VBA::vbIMEDisable),
    83, uint(VBA::vbIMEModeDisable),
    84, uint(VBA::vbIMEHiragana),
    85, uint(VBA::vbIMEModeHiragana),
    86, uint(VBA::vbIMEKatakanaDbl),
    87, uint(VBA::vbIMEModeKatakana),
    88, uint(VBA::vbIMEKatakanaSng),
    89, uint(VBA::vbIMEModeKatakanaHalf),
    90, uint(VBA::vbIMEAlphaDbl),
    91, uint(VBA::vbIMEModeAlphaFull),
    92, uint(VBA::vbIMEAlphaSng),
    93, uint(VBA::vbIMEModeAlpha),
    94, uint(VBA::vbIMEModeHangulFull),
    95, uint(VBA::vbIMEModeHangul),
    97, uint(VBA::vbOK),
    98, uint(VBA::vbCancel),
    99, uint(VBA::vbAbort),
    100, uint(VBA::vbRetry),
    101, uint(VBA::vbIgnore),
    102, uint(VBA::vbYes),
    103, uint(VBA::vbNo),
    105, uint(VBA::vbOKOnly),
    106, uint(VBA::vbOKCancel),
    107, uint(VBA::vbAbortRetryIgnore),
    108, uint(VBA::vbYesNoCancel),
    109, uint(VBA::vbYesNo),
    110, uint(VBA::vbRetryCancel),
    111, uint(VBA::vbCritical),
    112, uint(VBA::vbQuestion),
    113, uint(VBA::vbExclamation),
    114, uint(VBA::vbInformation),
    115, uint(VBA::vbDefaultButton1),
    116, uint(VBA::vbDefaultButton2),
    117, uint(VBA::vbDefaultButton3),
    118, uint(VBA::vbDefaultButton4),
    119, uint(VBA::vbApplicationModal),
    120, uint(VBA::vbSystemModal),
    121, uint(VBA::vbMsgBoxHelpButton),
    122, uint(VBA::vbMsgBoxRight),
    123, uint(VBA::vbMsgBoxRtlReading),
    124, uint(VBA::vbMsgBoxSetForeground),
    126, uint(VBA::vbUpperCase),
    127, uint(VBA::vbLowerCase),
    128, uint(VBA::vbProperCase),
    129, uint(VBA::vbWide),
    130, uint(VBA::vbNarrow),
    131, uint(VBA::vbKatakana),
    132, uint(VBA::vbHiragana),
    133, uint(VBA::vbUnicode),
    134, uint(VBA::vbFromUnicode),
    136, uint(VBA::vbUseDefault),
    137, uint(VBA::vbTrue),
    138, uint(VBA::vbFalse),
    140, uint(VBA::vbEmpty),
    141, uint(VBA::vbNull),
    142, uint(VBA::vbInteger),
    143, uint(VBA::vbLong),
    144, uint(VBA::vbSingle),
    145, uint(VBA::vbDouble),
    146, uint(VBA::vbCurrency),
    147, uint(VBA::vbDate),
    148, uint(VBA::vbString),
    149, uint(VBA::vbObject),
    150, uint(VBA::vbError),
    151, uint(VBA::vbBoolean),
    152, uint(VBA::vbVariant),
    153, uint(VBA::vbDataObject),
    154, uint(VBA::vbDecimal),
    155, uint(VBA::vbByte),
    156, uint(VBA::vbUserDefinedType),
    157, uint(VBA::vbArray),
    0 // eod
};

const QMetaObject Collection::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VBA__Collection, 0, 0, 0 }
};

void *Collection::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VBA::Collection"))
        return static_cast<void*>(const_cast<Collection*>(this));
    return QAxObject::qt_metacast(_clname);
}

