#ifndef ACCESSCVSADDINCONTROLLER_GLOBAL_H
#define ACCESSCVSADDINCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACCESSCVSADDINCONTROLLER_LIBRARY)
#  define ACCESSCVSADDINCONTROLLER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACCESSCVSADDINCONTROLLER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACCESSCVSADDINCONTROLLER_GLOBAL_H
