#ifndef HELPADDINCONTROLLER_GLOBAL_H
#define HELPADDINCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HELPADDINCONTROLLER_LIBRARY)
#  define HELPADDINCONTROLLER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define HELPADDINCONTROLLER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HELPADDINCONTROLLER_GLOBAL_H
